# Generated by Django 4.0.4 on 2022-12-09 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_remove_profit_loss_amount_remove_profit_loss_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mjournal',
            name='account1',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='account2',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='contact1',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='contact2',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='credit1',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='credit2',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='debit1',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='debit2',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='desc1',
        ),
        migrations.RemoveField(
            model_name='mjournal',
            name='desc2',
        ),
        migrations.CreateModel(
            name='mjournal1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('desc', models.TextField(null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('debit', models.CharField(default='', max_length=100)),
                ('credit', models.CharField(default='', max_length=100)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('mjrnl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.mjournal')),
            ],
        ),
    ]
