# Generated by Django 4.0.4 on 2022-12-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0061_alter_mjournal1_credit_alter_mjournal1_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mjournal1',
            name='credit',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='mjournal1',
            name='debit',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
    ]
