# Generated by Django 4.0.4 on 2022-12-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0062_alter_mjournal1_credit_alter_mjournal1_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='stockout',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
