# Generated by Django 4.0.4 on 2022-12-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_alter_itemtable_stockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='stockin',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
