# Generated by Django 4.0.4 on 2022-12-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0065_balance_sheet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
