# Generated by Django 4.0.4 on 2022-12-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0066_item_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='item1',
        ),
    ]
