# Generated by Django 4.0.4 on 2022-12-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0067_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='item',
        ),
    ]
