# Generated by Django 4.0.4 on 2022-12-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0067_rename_item_item1'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtable',
            name='amount',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
