# Generated by Django 4.0.4 on 2022-12-31 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0068_itemtable_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item1',
            new_name='itemstock',
        ),
    ]
