# Generated by Django 4.0.4 on 2022-12-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0068_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='opblnc_due',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
