# Generated by Django 4.0.4 on 2022-12-31 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0069_rename_item1_itemstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstock',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stockadjust'),
        ),
    ]
