# Generated by Django 4.0.4 on 2022-12-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0070_vendor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment1',
            name='amountdue',
            field=models.FloatField(null=True),
        ),
    ]
