# Generated by Django 4.0.4 on 2022-12-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_alter_purchasepayment1_amountdue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
