# Generated by Django 4.0.4 on 2022-12-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0071_itemstock_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjust',
            name='qty_hand1',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockadjust',
            name='qty_hand2',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockadjust',
            name='qty_hand3',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockadjust',
            name='qty_hand4',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockadjust',
            name='qty_hand5',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
