# Generated by Django 4.0.4 on 2022-12-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_alter_stockadjust_qty_hand1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjust',
            name='qty_hand1',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='stockadjust',
            name='qty_hand2',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='stockadjust',
            name='qty_hand3',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='stockadjust',
            name='qty_hand4',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='stockadjust',
            name='qty_hand5',
            field=models.IntegerField(default='0'),
        ),
    ]
