# Generated by Django 4.0.4 on 2022-12-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_alter_purchasepayment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='details',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='transactions',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
