# Generated by Django 4.0.4 on 2022-12-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_item_details_item_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='items',
        ),
    ]
