# Generated by Django 4.0.4 on 2022-12-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_item_details1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
