# Generated by Django 4.0.4 on 2022-12-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_alter_item_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='details1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
