# Generated by Django 4.0.4 on 2022-12-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_item_date_alter_item_details1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='details1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
