# Generated by Django 4.0.4 on 2022-12-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0078_alter_item_details1'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_sheet',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
