# Generated by Django 4.0.4 on 2022-12-23 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0079_balance_sheet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.invoice'),
        ),
    ]
